name: holdicon
favicon: null
layout_spectrum: 0.76452
typography_spectrum: 0.32781
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3948ff'
    - '#ffffff'
    - '#a2a9ff'
    - '#8891ff'
    - '#cdd1ff'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
